name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize and update submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libwayland-dev wayland-protocols libxkbcommon-dev libxrandr-dev libxinerama-dev
    
    - name: Clear CMake Cache
      run: rm -rf build/*

    - name: Configure CMake project
      run: cmake -B . -S . -DGLFW_BUILD_WAYLAND=OFF -DGLFW_BUILD_X11=ON
      
    - name: Build for Linux
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Package binaries
      run: zip -r HeronTriangle-Linux.zip ./build/bin/

    - name: Upload Linux Release
      uses: actions/upload-artifact@v3
      with:
        name: HeronTriangle-Linux
        path: HeronTriangle-Linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize and update submodules
      run: git submodule update --init --recursive
      
    - name: Configure CMake project
      run: cmake -B . -S .

    - name: Build for Windows
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Package binaries
      run: powershell -Command "Compress-Archive -Path build\bin\* -DestinationPath HeronTriangle-Windows.zip"

    - name: Upload Windows Release
      uses: actions/upload-artifact@v3
      with:
        name: HeronTriangle-Windows
        path: HeronTriangle-Windows.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: HeronTriangle-Linux
          path: ./linux
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: HeronTriangle-Windows
          path: ./windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/HeronTriangle-Linux.zip
            windows/HeronTriangle-Windows.zip
