name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Build for Linux
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        zip -r HeronTriangle-Linux.zip bin/

    - name: Upload Linux Release
      uses: actions/upload-artifact@v2
      with:
        name: HeronTriangle-Linux
        path: build/HeronTriangle-Linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v3

    - name: Build for Windows
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        powershell -Command "Compress-Archive -Path bin\* -DestinationPath HeronTriangle-Windows.zip"

    - name: Upload Windows Release
      uses: actions/upload-artifact@v2
      with:
        name: HeronTriangle-Windows
        path: build/HeronTriangle-Windows.zip

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Linux artifact
      uses: actions/download-artifact@v2
      with:
        name: HeronTriangle-Linux
        path: ./linux
  
    - name: Download Windows artifact
      uses: actions/download-artifact@v2
      with:
        name: HeronTriangle-Windows
        path: ./windows

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux/HeronTriangle-Linux.zip
          windows/HeronTriangle-Windows.zip
